#     dBP    dBBBBP dBBBBBBP dBP dBP.dBBBBP      dBBBBBb     dBP
#           dBP.BP                  BP                BB
#   dBP    dBP.BP    dBP   dBP dBP  `BBBBb        dBP BB   dBP
#  dBP    dBP.BP    dBP   dBP_dBP      dBP       dBP  BB  dBP
# dBBBBP dBBBBP    dBP   dBBBBBP  dBBBBP'       dBBBBBBB dBP
#
# Lotus is a Multi functional Personal asistant designed primerally for people
# like me, nerds, tech enthusiasts, gamers. she is fully customisable and can
# even be added to as users need
defaultMode: 0

modes:
  - pc
  - mobile
  - laptop
  - vheicle
  - home

interaction:
  - voice
  - terminal
  - ui

run:
  - run
  - launch
  - start
  - open

greetings:
  - hello
  - hey
  - heya
  - sup
  - whats up
  - hola
  - oi

disable:
  - disable
  - sleep
  - shutdown
  - deactivate
  - turn off
  - exit
  - end

enable:
  - start
  - enter
  - enable
  - wake
  - reactivate
